# Lines generated by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -e
# EOL generated by zsh-newuser-install

# Aliases
alias ls='ls --color=auto'
alias grep='grep --color=auto'

# Exports
export COLORTERM=truecolor

# Starship Prompt
eval "$(starship init zsh)"

# Plugins
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh


# bun completions
[ -s "/home/krish/.bun/_bun" ] && source "/home/krish/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
