# /etc/greetd/hyprland.conf

exec-once = dbus-run-session gtkgreet -l
monitor=,preferred,auto,1

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

animations {
    enabled = false
}
